export enum LoginTextEnum {
    typeCustomer = "ورود کاربران",
    typeWorker = "ورود متخصصین",
    rememberMe = "مرا به خاطر بسپار",
    forgetPassword = "رمز خود را فراموش کرده ام",
    question4Signup = "ثبت نام نکرده اید؟",
    mobileNumber = "شماره موبایل", 
    imageProfileUserTemp = "assets/webappPics/profileUser.png",
    imgAltProfileUserTemp = "لوگوی کاربر پالسین",
    password = "رمز عبور",
    repassword = "تکرار رمز عبور",
    loginToWeb = "ورود به سایت",
    signup = "ثبت نام",
    name = "نام",
    lastName = "نام خانوادگی",
    sendInfo = "ارسال اطلاعات",
    allFiledNecessary = "پر کردن تمامی فیلدهای این فرم الزامی است",
    verifySMSTitr = "کد پیامک ارسال شده را وارد کنید",
    timerText4ResendVerifySMS = "تا امکان مجدد ارسال کد تأیید",
    sendVerifyCode = "ارسال کد تأیید",
    reSendVerifyCode = "ارسال مجدد پیامک",
    register = "ثبت نهایی اطلاعات",
    back = "بازگشت",
    makeNewPassword = "ساخت رمز جدید",
}